name: sync
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  check-and-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Check for updates and sync
      run: |
        git remote add source https://github.com/different-ai/file-organizer-2000.git
        git fetch source master
        if [ "$(git rev-parse HEAD)" != "$(git rev-parse source/master)" ]; then
          echo "Changes detected, syncing repositories"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b temp_branch source/master
          git checkout main
          git rm -rf .
          git checkout temp_branch -- app
          git add .
          git commit -m "Sync app folder from source repository"
          git push origin main
        else
          echo "No changes detected"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
