name: sync
on:
  push:
    branches:
      - master
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Sync Repositories
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/different-ai/file-organizer-2000.git"
        source_branch: "master"
        destination_branch: "main"
        github_token: ${{ secrets.PAT }}
        source_root: "/app"
        destination_root: "/"
